### ISSUE TITLE
Installs LICENSE and README into the environment root

### ISSUE THREAD

**Issue by vfaronov** [tox-dev/filelock#14]
```
$ virtualenv env2
$ env2/bin/pip install filelock
$ ls env2
bin  include  lib  LICENSE.rst  local  pip-selfcheck.json  README.rst  share
```

These `LICENSE.rst` and `README.rst` appear because they are listed in filelock’s `setup.py` as `data_files`. It’s better to list them in a [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest) instead, so that they are included in a source distribution but are not actually installed.

**Comment by AdorablePotato** [comment]
Fixed it :)
