### ISSUE TITLE
Tags for releases

### ISSUE THREAD

**Issue by nicoddemus** [tox-dev/filelock#145]
Hi folks,

Would it be possible to use git tags for the releases? The latest release is `3.7.0`, however the latest tag is `v3.0.12`.

I maintain https://github.com/conda-forge/filelock-feedstock for the conda-package, and the tags help me seeing the diff between versions so I see any changes in dependencies or supported Python versions.

Thanks!

**Comment by gaborbernat** [comment]
We do have tags https://github.com/tox-dev/py-filelock/tags, every release creates a tag too 🤔

**Comment by nicoddemus** [comment]
Oh my bad, I looked at the top of the tags list on GitHub, but I see it changed the scheme from `vX.Y.Z` to `X.Y.Z`:

![image](https://user-images.githubusercontent.com/1085180/168306270-b1255e98-8e0f-4066-bcc8-6f2e98476796.png)

![image](https://user-images.githubusercontent.com/1085180/168306180-9d0eb053-5eea-48ad-825c-e79bbbd01353.png)


Sorry for the noise!
