### ISSUE TITLE
Please add simple use case on README.md

### ISSUE THREAD

**Issue by zackees** [tox-dev/filelock#146]
Hi, found this from a search. Please add the 4 line usage. I expect something like this:

```
LOCK_FILE = ...
LOCK = InterprocessLock(LOCK_FILE)

def foo():
    with LOCK:
        do_something()
```

Thanks

**Comment by gaborbernat** [comment]
It's already available within the official documentation linked from the reaadme https://py-filelock.readthedocs.io/en/latest/index.html#filelock

**Comment by zackees** [comment]
Why not just copy and paste this snippet
```
from filelock import Timeout, FileLock

lock = FileLock("high_ground.txt.lock")
with lock:
    with open("high_ground.txt", "a") as f:
        f.write("You were the chosen one.")
```

Into the readme? The documentation link is great, but I can't find a link to it from the github/docs. This little snippet would answer the question that every single new user has when they visit the product: "how does this work?"

**Comment by gaborbernat** [comment]
Because we don't want to duplicate information, and the README is not documentation. The Readme has a direct link to the actual documentation. Users should only consult the documentation to find the answer, and is accessible from the readme via the link to it.

**Comment by zackees** [comment]
The readme is special, because it is pushed all the way to the pypi page where people are browsing for solutions like what you have.

Look it's your software, you can do whatever, I'm just pointing out a glaring UX issue that can be fixed in under a minute. Your simple use case isn't laid out in any connecting links. I have to grep and understand all the components just to put out the correct four lines of code to get the project up and running. And the first time I used a softlock which was the wrong construct.

**Comment by gaborbernat** [comment]
> The readme is special, because it is pushed all the way to the pypi page where people are browsing for solutions like what you have.

I think we'll need to agree to disagree on this.

**Comment by gaborbernat** [comment]
I did update the documentation link in the readme to point from the API page to the index page - https://github.com/tox-dev/py-filelock/commit/4730a40b87cc4b094330b2af7723658428323d60

**Comment by zackees** [comment]
Ah i see. Thanks
