### ISSUE TITLE
Does this library support distributed file lock?

### ISSUE THREAD

**Issue by speedcell4** [tox-dev/filelock#161]
Hi~ 

If I have a shared file directory among several nodes, I start several processes on each node separately.
Does this library ensure only one process may enter the `with FileLock` context at any time among all these nodes?

**Comment by gaborbernat** [comment]
Assuming the directory is shared across nodes and the filesystem in question supports the OS level locking methods, yes it should.

**Comment by speedcell4** [comment]
Thank you~
