### ISSUE TITLE
Some tests fail on systems where flock is emulated with fcntl

### ISSUE THREAD

**Issue by kulikjak** [tox-dev/filelock#165]
I wanted to report that on some systems (in my case Oracle Solaris), several tests won't pass because of incorrect test suite assumptions. When native `flock()` is available, locking works per file description and two locks in the same process can "fight" over the same thing. But on systems where [`fcntl.flock()`](https://docs.python.org/3/library/fcntl.html#fcntl.flock) is emulated using `fcntl()`, this doesn't work because standard `fcntl` is locking per process, and thus trying multiple locks in the same one will never fail.

It's basically the same as calling something like this on Linux:
```python
import os
import struct
import fcntl

open_mode = os.O_RDWR | os.O_CREAT | os.O_TRUNC
fd = os.open("a", open_mode)
op = struct.pack('hhllhhl', fcntl.F_WRLCK, 0, 0, 0, 0, 0, 0)
fcntl.fcntl(fd, fcntl.F_SETLK, op)

fd = os.open("a", open_mode)
op = struct.pack('hhllhhl', fcntl.F_WRLCK, 0, 0, 0, 0, 0, 0)
fcntl.fcntl(fd, fcntl.F_SETLK, op)
```
it also won't fail (but replacing `fcntl.fcntl(...)` with `fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)` will result in the second one failing).

That said, between processes, it works as expected so this is just about the test suite.

**Comment by gaborbernat** [comment]
I'm not sure if we can do anything about this. We don't support explicitly Oracle Solaris, but assuming we would is there some OS level functionality that would allow us to do so?

**Comment by kulikjak** [comment]
Unfortunately, I don't think so :( - I believe that, in a single process, the expectation is that `mutex` will be used instead. The only thing that comes to mind is to use IPC and named semaphores. That said, that has nothing to do with file locking and is well outside of the scope of this library.

I think there's nothing to worry about - I just wanted to report this for posterity. Also, it only affects `UnixFileLock`; `SoftFileLock` passes all tests. And since we are integrating filelock to use it with new virtualenv which seems to use these locks for inter-process locking (and that works as expected), it works for us.

**Comment by gaborbernat** [comment]
Sounds good, thanks for the report.
