### ISSUE TITLE
Unintuitive behavior (releasing the lock in __del__)

### ISSUE THREAD

**Issue by snowwm** [tox-dev/filelock#173]
It took me a long time debugging and reading the source code to understand why the lock did't work. My code was like this:

```python
FileLock(".lock").acquire()
# do stuff
```

At the end I discovered that the lock gets released immediately because there's no reference to the lock object left in the program. I find this behavior disputable. Isn't it a valid usage pattern to acquire a lock and hold it until the end of program? Then, isn't it natural to write code like I did? If there are reasons to release the lock on object destruction, then at least this behavior should be **well-documented**.

**Comment by gaborbernat** [comment]
> ```python
> FileLock(".lock").acquire()
> # do stuff
> ```

There's no such example in our documentation, https://py-filelock.readthedocs.io/en/latest/index.html#filelock.

> At the end I discovered that the lock gets released immediately because there's no reference to the lock object left in the program. I find this behavior disputable. Isn't it a valid usage pattern to acquire a lock and hold it until the end of program?

It might be, but if that's the case is your responsibility to register the lock release via https://docs.python.org/3/library/atexit.html, this library does not do it for yourself.
