### ISSUE TITLE
Fix the license classifier in distribution to the "Unlicense"

### ISSUE THREAD

**Issue by jond01** [tox-dev/filelock#179]
The package is licensed under the ["Unlicense"](https://github.com/tox-dev/py-filelock/blob/main/LICENSE), but the PyPI distribution uses the following classifier:
https://github.com/tox-dev/py-filelock/blob/579ccc3412f2b370d7be64a9616f5d01d1f2e676/setup.cfg#L14
It's better to be changed to the following [classifier](https://pypi.org/classifiers/):
```
License :: OSI Approved :: The Unlicense (Unlicense)
```

**Comment by gaborbernat** [comment]
PR welcome.
