### ISSUE TITLE
filelock is erasing file contents

### ISSUE THREAD

**Issue by zauberparacelsus** [tox-dev/filelock#19]
I was trying out this library, but found that opening a file for reading while under a lock would completely erase the file's contents.

The following code reproduces the issue:
```
#!/usr/bin/python3

import filelock

with open("test.txt", "w") as f:
	f.write("This is some testing text")

lock = filelock.FileLock("test.txt")
with lock:
	with open("test.txt", "r") as f:
		a = f.read()
		print(a)
```

* This issue occurs on 64bit Ubuntu 17.04, using Python 3.5.3
* I have no idea if there is a particular way I am supposed to open files with filelock.  If there is, it wasn't covered in the readthedocs page, which has absolutely no information on reading or writing files.

**Comment by zauberparacelsus** [comment]
An additional note: if you open the test.txt file after running this script, the file actually is empty, it's not just being misread as empty.

**Comment by mokelly** [comment]
I also thought at first that the purpose of this library was to prevent simultaneous access to the specified file (`test.txt` in your example), but that may be mistaken.  If I understand correctly now, to lock `test.txt` you want to choose a different name for the lockfile, e.g.

`lock = filelock.FileLock("test.txt.lock")`

Now, as long as every process that wants to use `test.txt` must first acquire the lock on `test.txt.lock`, `test.txt` will be protected.  However, `test.txt` won't be protected from any programs that don't care about your lock.
