### ISSUE TITLE
[documentation] Beginners view on the README

### ISSUE THREAD

**Issue by dneise** [tox-dev/filelock#22]
Hello! I think this is a great package. Maybe you are interested in an outsiders view at the README. 

Use case: I was about to write to processes which were *supposed* to run at different times and both would update the same file. Since I cannot guarantee that one process would not take much longer than anticipated, I thought about ways for these processes to communicate. I heard about lock files so I googled for python implementations, as I also heard one needs to be careful with this stuff and use a lot of atomic operations ... stuff I have no idea about. 
I found these packages:

 * [lockfile 0.12.2](https://pypi.python.org/pypi/lockfile/0.12.2) which says it is **deprecated**
 * [filelock 2.0.12](https://pypi.python.org/pypi/filelock) which is already a version 2 not zero, so it created a feeling of trustworthyness. :+1: 

Then I read the README (on pypi)

 >  [...] This means, when locking the same lock object twice, it will not block.

This puzzled me a lot. I thought: "Isn't blocking exactly the expected behaviour of a lockfile? when somebody already has aquired the lock?"

So I tested it using two ipython sessions:

Upper:
```ipython
In [1]: from filelock import FileLock
In [2]: lock = FileLock('.lock')
In [3]: lock.acquire()
Out[3]: <filelock.BaseFileLock.acquire.<locals>.ReturnProxy at 0x...>
```

Lower:
```ipython
In [1]: from filelock import FileLock
In [2]: lock = FileLock('.lock')
In [3]: lock.acquire()
# it blocks!
```

----

So your package works exactly as I expected it to work **before** reading the README. After reading the README I was puzzled, and after testing I was happy again. 

Now after reading a bit more ... I think I get the point that sentence is trying to make. Apparently **inside the same process** `acquire()`-ing the same lock multiple times does not block the process itself. As a beginner I can not imagine why one would actually want to acquire the lock multiple times within the same process, but I guess there are use cases. 

I was wondering if you would like to smooth out the path for using your great package for beginners a little bit. Maybe one could be a bit more elaborate in the first part of the README. So after this:

> This package contains a single module, which implements a platform independent file lock in Python.

 one could maybe say:

> File locking is a mechanism that restricts access to a computer file by allowing only one process to access it in a specific time. Another process trying to `acquire` the same FileLock will block.

And then further down

> The lock includes a lock counter and is thread safe. This means, when [the same process] is acquiring the same lock object twice, it will not block.

----

I could make a PR for this if you like.

**Comment by AdorablePotato** [comment]
Hi, sorry for the late reply, I'm currently learning for some exams. 
I see your point.

> The lock includes a lock counter and is thread safe. This means, when [the same process] is acquiring the same lock object twice, it will not block.

 I think I should have used the term *reentrant lock* here. Each filelock *instance* is one. 

> File locking is a mechanism that restricts access to a computer file by allowing only one process to access it in a specific time. Another process trying to acquire the same FileLock will block.

Since *each* filelock instance defines a reentrant lock, two *different* instances (whether they are in the same process/thread or not) will block during locking when the other instance already holds the lock. But locking the *same* instance twice while not block.

I'd happily accept a pull request which describes the locking behavior more appropriate :)
