### ISSUE TITLE
filelock.py gets logger on global level

### ISSUE THREAD

**Issue by vladak** [tox-dev/filelock#24]
https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/ explains why this is not a good practice.

**Comment by AdorablePotato** [comment]
I updated the code so that the logger is first acquired when needed.

I'm a bit courious, is there a reason why the [disable_existing_loggers](https://docs.python.org/3.6/library/logging.config.html#logging.config.fileConfig) command is not sufficient or not an option?

**Comment by avatar-lavventura** [comment]
How could I disable filelock's logging?

**Comment by AdorablePotato** [comment]
Disable propagation via https://docs.python.org/3/library/logging.html#logging.Logger.propagate
```python
logger = filelock.logger()
logger.propagate = False
```
or set the level of the logger high enough.
