### ISSUE TITLE
The type annotation for the `lock_file` `__init__` parameter is too narrow

### ISSUE THREAD

**Issue by exarkun** [tox-dev/filelock#258]
`BaseFileLock.__init__` annotates `lock_file` as `str | os.PathLike[Any]`.  However, this excludes `bytes` which are still the basic representation of paths on most POSIX systems.  The implementation goes on to pass `lock_file` to `os.fspath` which both accepts and may return `bytes` values so there doesn't seem to be any reason to exclude `bytes` from the annotation.

**Comment by gaborbernat** [comment]
PR welcome 👍
