### ISSUE TITLE
Using filelock in docker

### ISSUE THREAD

**Issue by arunpt** [tox-dev/filelock#287]
Right now, I'm serving multiple instances of my app on a server, and `filelock` is working perfectly as expected by acquiring and releasing locks, even when multiple requests come in simultaneously. If I'm scaling my application using **Docker** and **Kubernetes**, I'm concerned about how `filelock` is going to behave since each container is independent of each other. I'm planning to mount a shared storage that would be accessible to all the containers. Will it help in any case, or is there any approach available to achieve the present behavior across **multiple** Docker containers?

**Comment by gaborbernat** [comment]
Depending on your file system, I cannot answer you must try and see 👍
