### ISSUE TITLE
Filelock deletes file in 2.0.14!

### ISSUE THREAD

**Issue by ecamaj** [tox-dev/filelock#29]
Deployed new version of system and it grabbed new version of filelock and this part of code actually deletes file in file_path variable!

```
    file_path = get_project_path(project_slug) + '/' + settings.PROJECT_JSON
    with FileLock(file_path):
        project_file = open(file_path, 'w')
        project_file.write(json.dumps(data))
        project_file.close()
```

I've put print `os.path.exists` just before and after this part of code and this is from log:

```
True
2017-12-30 21:00:33,622 - filelock - DEBUG - Attempting to acquire lock 140185207182392 on /.../project.json
2017-12-30 21:00:33,622 - filelock - INFO - Lock 140185207182392 acquired on /.../project.json
2017-12-30 21:00:33,622 - filelock - DEBUG - Attempting to release lock 140185207182392 on /.../project.json
2017-12-30 21:00:33,623 - filelock - INFO - Lock 140185207182392 released on /.../project.json
False
```

DO NOT INSTALL LATEST VERSION or you might have your files deleted!

**Comment by ecamaj** [comment]
Downgraded to 2.0.13, all seems ok again.

**Comment by AdorablePotato** [comment]
I hope you did not lose any data. This behavior is a consequence of fix #27. As the README states, the lockfile is always empty (https://github.com/benediktschmitt/py-filelock#what-this-filelock-is-not).

However, I should have increased the major version number and not a minor one. I removed the latest version from PyPi for the moment. Please note, that the intended way to use the file lock is:
```Python
with FileLock(file_path + ".lock"):
  project_file = open(file_path, 'w')
  # ...
```

**Comment by mje-nz** [comment]
Hi Benedikt,

The new behaviour is exactly what I was expecting; that's what lock files are supposed to do. I came here to report the lock file not being deleted in 2.0.13 as a bug!

When are you going to release a new version with #27 included?

Thank you for your work :)

**Comment by AdorablePotato** [comment]
version 3.0.0 is on PyPi now
