### ISSUE TITLE
using with and providing a timeout

### ISSUE THREAD

**Issue by benprew** [tox-dev/filelock#3]
I'd like to be able to use the `with` and specify a timeout.

Doing this:

```
with self.lock.acquire(timeout=10):
```

Results in a nested lock (since `__enter__` acquires a lock too).  I couldn't see a way to do this without explicitly releasing the lock.

Any suggestions for how to use with and timeout together?

Thanks

**Comment by AdorablePotato** [comment]
At the moment, there is no other way. Would a fix of issue #2 help you?

There would still be the problem with providing a timeout value in the with statement. I don't want to change the behavior of the _acquire_ method for backward compatibility, but I could implement the `__call__` method to allow you doing this:

``` python
with self.lock(timeout = 10):
```

I'm open for any ideas.

**Comment by AdorablePotato** [comment]
I noticed now, that I broke the API with the reference counter, since your example worked before.

**Comment by benprew** [comment]
I think the `__call__` method idea sounds good, my python skills aren't great, so you probably have better ideas than I do :)

**Comment by AdorablePotato** [comment]
I fixed this issue in the _dev_ branch. You can now use the _acquire()_ method also in the with statement without side effects. So this works now:

``` python
with lock.acquire(timeout = 10):
  assert lock.is_locked
  with lock.acquire(timeout = 10):
    assert lock.is_locked
assert (not lock.is_locked)
```

I will upload the new version in the next days.

**Comment by benprew** [comment]
Awesome, thanks for making the change so quickly!
