### ISSUE TITLE
Python 3.7 support dropoff at version 3.12.3 not reflected in 'Security' section

### ISSUE THREAD

**Issue by JeffViviani** [tox-dev/filelock#301]
[Version 3.12.2](https://pypi.org/project/filelock/3.12.2/) on PyPi seems to be the last version to indicate Python 3.7 support exists.
[Version 3.12.3](https://pypi.org/project/filelock/3.12.3/) indicates only >=3.8 is supported.

However, the Security section on the main GitHub page of this repo indicates Python 3.7 + is good for the latest release.

**Comment by gaborbernat** [comment]
Yeah, bug in the security part. PR welcome 👍
