### ISSUE TITLE
Random assertions failing in test.py 

### ISSUE THREAD

**Issue by satta** [tox-dev/filelock#31]
I'm maintaining py-filelock for Debian (https://packages.qa.debian.org/p/python-filelock.html). We are running`test.py` in a clean chroot during the package build to verify that all tests pass in the version to be packaged. However, we recently noticed that current versions of the library fail their `test.py` runs with random assertions being hit:

```
PYTHONPATH=. python2 /build/python-filelock-3.0.0/debian/test.py
.........FF..F........
======================================================================
FAIL: test_threaded1 (__main__.FileLockTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-filelock-3.0.0/debian/test.py", line 233, in test_threaded1
    threads1[i].join()
  File "/build/python-filelock-3.0.0/debian/test.py", line 66, in join
    raise (wrapper_ex.__class__, wrapper_ex, self.ex[2])
AssertionError

======================================================================
FAIL: test_timeout (__main__.FileLockTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-filelock-3.0.0/debian/test.py", line 253, in test_timeout
    self.assertRaises(filelock.Timeout, lock2.acquire, timeout=1)
AssertionError: Timeout not raised

======================================================================
FAIL: test_default_timeout (__main__.SoftFileLockTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-filelock-3.0.0/debian/test.py", line 278, in test_default_timeout
    self.assertRaises(filelock.Timeout, lock2.acquire)
AssertionError: Timeout not raised

----------------------------------------------------------------------
Ran 22 tests in 6.045s
```

Patching the source to revert cb1d83d6cb18cc60fb6249fa59e2b47631161244 seems to reliably fix the issue but I'm not sure stray lock files are left lying around. Any comments?

**Comment by AdorablePotato** [comment]
The test for the SoftFileLock fails only because of the FileLockTest. This is a bug in the *test.py* module. So the SoftFileLock is fine.

The bug in the FileLock is probably caused by the race conditions described in this [stackoverflow question](https://stackoverflow.com/questions/17708885/flock-removing-locked-file-without-race-condition). Because the lock file is meant as a simple synchronization mechanism, I think the best solution would be to revert cb1d83d6cb18cc60fb6249fa59e2b47631161244, although not very satisfying.

Side note: Do you know if this bug exists under windows too?

**Comment by satta** [comment]
> The bug in the FileLock is probably caused by the race conditions described in this stackoverflow question. Because the lock file is meant as a simple synchronization mechanism, I think the best solution would be to revert cb1d83d, although not very satisfying.

OK. I've added this patch to the package for now.

> Side note: Do you know if this bug exists under windows too?

No idea, unfortunately I don't have a Windows system around at the moment to test.

**Comment by AdorablePotato** [comment]
I think I can close this issue. If the bug still occurs, feel free to reopen it.
