### ISSUE TITLE
Locks across machines

### ISSUE THREAD

**Issue by mzakharocsc** [tox-dev/filelock#33]
Hello, I am trying to implement locking across machines. However,  SoftFileLock can deadlock sometimes if process ends abruptly. Are there any other solutions that can ensure that deadlocks do not occur?

**Comment by AdorablePotato** [comment]
Sorry, but at the moment that's not possible, you need to take care of that yourself. Perhaps store some PID or timestamp with the last access in another file, check them before locking or use a timeout.
