### ISSUE TITLE
'_CountedFileLock' object has no attribute 'thread_safe'

### ISSUE THREAD

**Issue by gaborbernat** [tox-dev/filelock#337]
This (via the 3.15.0 release) may be responsible for breaking virtualenv. See https://github.com/pypa/virtualenv/issues/2735.

_Originally posted by @tamird in https://github.com/tox-dev/filelock/issues/334#issuecomment-2163658727_

**Comment by gaborbernat** [comment]
cc @ ethanbb

**Comment by crgwbr** [comment]
Happening to me too. Stacktrace:

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/python', '-mvirtualenv', '<FOOO>/.cache/pre-commit/repou424sxk0/py_env-python3.12')
return code: 1
stdout:
    RuntimeError: failed to build image pip because:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.12/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.12/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.12/site-packages/virtualenv/util/lock.py", line 22, in __init__
        super().__init__(lock_file)
    TypeError: object.__init__() takes exactly one argument (the instance to initialize)
stderr:
    Exception ignored in: <function BaseFileLock.__del__ at 0x77ffd0526ac0>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.12/site-packages/filelock/_api.py", line 365, in __del__
        self.release(force=True)
      File "/usr/local/lib/python3.12/site-packages/virtualenv/util/lock.py", line 34, in release
        with self.thread_safe:
             ^^^^^^^^^^^^^^^^
    AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

**Comment by gaborbernat** [comment]
cc @ethanbb

**Comment by chrisrossi** [comment]
I just encountered this using nox on a project:

```
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
Exception ignored in: <function BaseFileLock.__del__ at 0x7f49d3407250>
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/dclimate/lib/python3.10/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/home/chris/.virtualenvs/dclimate/lib/python3.10/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

Started whenever 3.15 hit pypi.

**Comment by tamird** [comment]
@gaborbernat seems like an immediate yank would be good.

**Comment by CNDW** [comment]
happening to me as well, all of our builds in CI stopped building with this error -> the `virtualenv` package depends on this one so I suspect this is a very widespread failure.

I've been seeing it on python 3.11.9

**Comment by jfoxtech** [comment]
Also encountering when trying to spin up a venv via poetry:

```
Exception ignored in: <function BaseFileLock.__del__ at 0x7fc53764b6d0>
Traceback (most recent call last):
  File "/home/runner/.local/venv/lib/python3.10/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/home/runner/.local/venv/lib/python3.10/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

**Comment by gaborbernat** [comment]
<img width="758" alt="image" src="https://github.com/tox-dev/filelock/assets/690238/c1931dfc-656d-4890-b20d-01df3066819a">

**Comment by vasiminamdar** [comment]
Below traceback running `virtualenv venv`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
    with parent.non_reentrant_lock_for_key(wheel_img.name):
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/virtualenv/util/lock.py", line 1[42](https://gitlab.com/ftdr/devops/tools/deployinator/-/jobs/7085218033#L42), in non_reentrant_lock_for_key
    with _CountedFileLock(str(self.path / f"{name}.lock")):
  File "/usr/local/lib/python3.9/site-packages/virtualenv/util/lock.py", line 22, in __init__
    super().__init__(lock_file)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)`

**Comment by NickDunkman** [comment]
Thanks @gaborbernat!

**Comment by conradogarciaberrotaran** [comment]
Any way to force poetry to use filelock 3.14.0?

**Comment by johnthagen** [comment]
Now that `filelock` 3.15.0 is yanked, any bare installs of `pip install poetry==N` will no longer select `filelock` 3.15.0 as a sub dependency. Our CI is working again.

**Comment by jfoxtech** [comment]
@conradogarciaberrotaran See above, as I already tried that path. All is well now on my end as well!

**Comment by conradogarciaberrotaran** [comment]
Re-running fixed everything! I was worried our cache would still use 3.15.0 but it's not the case.

**Comment by cheginit** [comment]
Just wanted to let you know that v3.15 still exists on `conda-forge`, so envs that are created with `conda` will fail due to this error.

**Comment by gaborbernat** [comment]
> Just wanted to let you know that v3.15 still exists on `conda-forge`, so envs that are created with `conda` will fail due to this error.

I do not control conda, so that will be fixed by someone else.

**Comment by fattybenji** [comment]
This issue happens again with version 3.15.2 in my CI. Context: creating a virtualenv with poetry by running poetry install. Python 3.12. Full stack below. Should I open a new issue ?

```
Creating virtualenv lambda-functions-P30EH11U-py3.12 in /root/.cache/pypoetry/virtualenvs
Exception ignored in: <function BaseFileLock.__del__ at 0xf23383f01da0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/filelock/_api.py", line 388, in __del__
    self.release(force=True)
  File "/usr/local/lib/python3.12/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
         ^^^^^^^^^^^^^^^^
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
failed to build image pip because:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
    with parent.non_reentrant_lock_for_key(wheel_img.name):
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
    with _CountedFileLock(str(self.path / f"{name}.lock")):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/filelock/_api.py", line 117, in __call__
    instance = super().__call__(
               ^^^^^^^^^^^^^^^^^
TypeError: _CountedFileLock.__init__() got an unexpected keyword argument 'timeout'
```

**Comment by Czaki** [comment]
Your error is caused by filelock 3.15.2 release that already is yanked from pypi https://pypi.org/project/filelock/#history

**Comment by prescod** [comment]
Yes, something strange is happening in github or Poetry or something. Somehow in the last hour its started picking up the yanked version of filelock. :( I know there is nothing the filelock maintainers can do about it, but this is the only context to discuss it which Google will turn up for people.

**Comment by prescod** [comment]
Poetry has not had a release. virtualenv has not had a release. I don't know what project is picking up the yanked version of filelock.

**Comment by Czaki** [comment]
Problematic version is released 34 minutes ago, and yanked few minutes later

**Comment by nils-borrmann-tacto** [comment]
Fyi: I also experienced this issue on the (non-yanked) release 3.15.1. Downgrading to 3.14.0 helped.

**Comment by alex-pope-l3** [comment]
We also had breakages due to version 3.15.2.  Downgrading to 3.14.0 fixed the problem for us too.

**Comment by hanssl** [comment]
Why hasn't 3.15.1 been yanked?

**Comment by ethanbb** [comment]
Can someone post an error they got from 3.15.1? I don't believe it could be the same problem....changes in the last release (3.15.2) clearly created the new issue, which is different from the one in 3.15.0.

**Comment by ethanbb** [comment]
> This issue happens again with version 3.15.2 in my CI. Context: creating a virtualenv with poetry by running poetry install. Python 3.12. Full stack below. Should I open a new issue ?

It's a different error, so probably yes

**Comment by hanssl** [comment]
![Screenshot 2024-06-19 at 9 31 00 AM](https://github.com/tox-dev/filelock/assets/649957/a7dead1e-7cf2-4bf6-8a44-36e7f43fef49)

**Comment by gaborbernat** [comment]
> Why hasn't 3.15.1 been yanked?

It has been.

**Comment by hanssl** [comment]
![Screenshot 2024-06-19 at 9 33 39 AM](https://github.com/tox-dev/filelock/assets/649957/1d8e2738-7271-472c-98ce-cfb90cfe306f)

**Comment by gaborbernat** [comment]
> ![Screenshot 2024-06-19 at 9 31 00 AM](https://github.com/tox-dev/filelock/assets/649957/a7dead1e-7cf2-4bf6-8a44-36e7f43fef49)
> 

Please provide version information via pip of the packages installed. That doesn't look like 3.15.1.

**Comment by ethanbb** [comment]
Yes looks like your code is still using 3.15.2. The code producing the error didn't exist when 3.15.1 was released.

**Comment by hanssl** [comment]
You are correct, I am on a mirrored pypi that is still pulling in 3.15.2 to my poetry environments.

**Comment by hanssl** [comment]
filelock 3.15.3 still broken

![Screenshot 2024-06-19 at 10 42 10 AM](https://github.com/tox-dev/filelock/assets/649957/a48ef7f1-d2ea-406f-923f-0e696cd51589)

**Comment by kwist-sgr** [comment]
@hanssl This isn't like 3.15.3.
stack trace is the same as here https://github.com/tox-dev/filelock/issues/337#issuecomment-2178987654

**Comment by hanssl** [comment]
> @hanssl This isn't like 3.15.3. stack trace is the same as here [#337 (comment)](https://github.com/tox-dev/filelock/issues/337#issuecomment-2178987654)

Maybe I am missing something?  I deleted my poetry venv, created a new one, and ran poetry install (verified the 'Installing filelock (3.15.3) line).  I then run 'docker build...' from that poetry env and I got the error above.

**Comment by johnthagen** [comment]
@hanssl You might have an old/broken `filelock` installed _into_ Poetry's internal virtual environment. You may need to uninstall Poetry and reinstall it so that it picks a non-yanked `filelock` when _Poetry_ itself is installed.

Note, this kind of issue is why a while ago I opened

- https://github.com/python-poetry/poetry/issues/7990

So that it would not be possible for Poetry users to install Poetry with dependencies it hadn't tested/validated in its CI.
