### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by berkowitze** [tox-dev/filelock#34]
I'm writing a program with a lot of file reading/writing, so I'm trying to make the code more manageable.

I'd like a function like this:
```python
def locked_open(filename, mode='r'):
    lock = FileLock(filename)
    with lock:
        <not sure what to put here, return open(filename, mode) doesn't work>

....

with locked_open(filename, mode):
    <do stuff>
```

Can you think of a way to do this?

**Comment by berkowitze** [comment]
Not sure if this is Pythonic or even correct (I don't have too much experience with `__enter__` and `__exit__`) but here's a potential solution:
```python
class LockedFile(object):
    def __init__(self, filename, mode='r'):
        self._fn = filename
        self._mode = mode

    def __enter__(self):
        self._lock = FileLock('%s.lock' % self._fn)
        self._lock.acquire()
        self._f = open(self._fn, self._mode)
        return self._f

    def __exit__(self, a, b, c):
        self._lock.release()
        self._f.close()

with LockedFile('hello.txt', 'w'):
    print 'hello'
```

**Comment by AdorablePotato** [comment]
I'd use the contextmanager decorator, it's quite nifty.

```python
from contextlib import contextmanager
from filelock import FileLock

@contextmanager
def locked_open(filename, mode):
        lock = FileLock(filename + ".lock")
        with lock, open(filename, mode) as f:
                yield f
        return None

with locked_open("my_file.txt", "w") as f:
        f.write("Hello")

with locked_open("my_file.txt", "r") as f:
        print(f.read())
```

I don't know your use case, but if you deal with a lot of files, you may want to try other, more efficient ways of interprocess communication.

**Comment by berkowitze** [comment]
Is there a good way to clean up all the .lock files after without running something like os.remove?

**Comment by AdorablePotato** [comment]
You could place them all inside a temporary directory and let the OS take care of that. This makes also sure, that they are not accidentally deleted when still in use.

https://docs.python.org/3.7/library/tempfile.html
