### ISSUE TITLE
Filelock depending on virtualenv can be flaky with "cannot import name 'fs_path_id' from 'virtualenv.info'"

### ISSUE THREAD

**Issue by crdrost** [tox-dev/filelock#358]
Hi there! Ran into this at work, figured you might want to know, if only to have a ticket to cite that blames it on some other project if someone else runs into the same issue that I did.

**Summary**: A cyclic dependency introduced in `filelock@3.15.3`, combined with a Poetry virtual environment that is preloaded with older versions of `virtualenv` and `filelock`, can break `poetry install` as it tries to upgrade both simultaneously and runs into some confusion about the two virtualenv installs that it is working with.

**Background**: `filelock@3.15.2` broke `virtualenv` which depends on it, so `filelock@3.15.3` fixed and added a `package.extras` dependency which depends on `virtualenv >= 20.26.2`. So you have this weird dependency cycle. Meanwhile `virtualenv@20.26.1` added a new function to `virtualenv.info` called `fs_path_id` that it imports in some places. 

I am a contractor for a team at Apple, I probably can't disclose most of what I'm working on, but I can probably say that Apple has an internal CI/CD platform with a [Poetry](https://python-poetry.org/) module that I wanted to use, and that's how I ran into this strange state-of-affairs. I actually don't use either `filelock` or `virtualenv` myself, this was a transitive dependency of `splunk-sdk` (which is headache-inducing in other ways!).

**What happened**: So our CI/CD Poetry module comes with a virtual environment that's already initialized with some packages. In the logs I can see,

```txt
     + poetry install
     Installing dependencies from lock file
     
     Package operations: 24 installs, 8 updates, 0 removals
   [...]
       - Updating filelock (3.13.4 -> 3.15.4): Pending...
   [...]
       - Updating virtualenv (20.25.1 -> 20.26.3): Pending...
   [...]
       - Installing splunk-sdk (2.0.2): Failed
     
       ImportError
     
       cannot import name 'fs_path_id' from 'virtualenv.info' (/opt/venv/lib64/python3.11/site-packages/virtualenv/info.py)
     
       at /opt/venv/lib64/python3.11/site-packages/virtualenv/discovery/builtin.py:9 in <module>
             5│ import sys
             6│ from pathlib import Path
             7│ from typing import TYPE_CHECKING, Callable
             8│ 
         →   9│ from virtualenv.info import IS_WIN, fs_path_id
            10│ 
            11│ from .discover import Discover
            12│ from .py_info import PythonInfo
            13│ from .py_spec import PythonSpec
     
     Cannot install splunk-sdk.
```

This applies even if we pin `poetry add virtualenv@20.25.1`, the transitive dependency from Poetry still wants to install `extras` on `poetry install` which upgrades to 20.26.3 (might be a bug in Poetry?) but the problem can go away if we pin `poetry add filelock@3.15.1`.

That should be enough info to generate a minimal example, I believe the terms of my contract preclude me from actually constructing one with this laptop as hardware?

**Comment by gaborbernat** [comment]
This sounds to me like a bug inside poetry.
