### ISSUE TITLE
Json load and Filelock

### ISSUE THREAD

**Issue by jenson86** [tox-dev/filelock#4]
Hey Benedikt,

i'm really new to Python and work for a state monitoring for a RPi and different functions with the internal Watchdog at the moment. 

I tried the following, but it doesn't work because either pemission denied in Windows or there is no file anymore (Raspbian):

``` python
path='ConfigLED.json'
lock=filelock.FileLock(path)

with lock:
    with open(path) as config:
        data=json.load(config)

    print(data)
lock.release(True)
```

I think the problem is, that the lock is to the file and only with the object, which is combined with the lock, I can load the data. But the property (fd) is privat, right? Can you help me, how to realize that or is it not possible?

BR Jens

**Comment by AdorablePotato** [comment]
Hi,

this code should work:

``` python

path='ConfigLED.json'
lock=filelock.FileLock(path + "lock")

with lock:
    with open(path) as config:
        data=json.load(config)

    print(data)
```

What the _FileLock_ does, is to create a new file (in this case _path + "lock"_) and locks it. If another instance of your application starts and wants to acquire the lock too, it must wait until the other instance releases the lock.

The purpose of this module is too prevent having multiple instances of your application modifying resources on the hard drive to the same time.
So the file used by the _FileLock_ is always empty. We only lock it and watch its existence.

If only one single instance of your application is running to the same time, you don't need the filelock. 

I wrote this module to the same time as my minecraft manager. The manager runs also as cron job and so I had the fear, two instances could sent conflicting commands at the same time to a minecraft world. When the manager now starts, It waits until it can acquire a _FileLock_. When it acquired the lock, the application continues with the execution. This way, I can assert, only one instance sents commands at the same time.

**Comment by jenson86** [comment]
Hey,

thanks a lot for your reply. It works fine. After your description I recognized the main principle. Thanks!

Jens

**Comment by AdorablePotato** [comment]
I'm glad I could help :)
