### ISSUE TITLE
test.py is missing from pypi tarball

### ISSUE THREAD

**Issue by dimon222** [tox-dev/filelock#48]
... hence not able to run tests if using pypi tarball.

**Comment by selurvedu** [comment]
+1

**Comment by AdorablePotato** [comment]
I'll include them in the new version, after #47 is merged.

**Comment by AdorablePotato** [comment]
#47 has some side-effects, so I'll delay the merge. The new packages are now on PyPi (v3.0.11), hopefully including the tests and a fixed documentation if I did not mess something up.
