### ISSUE TITLE
document seems to have error with respect to timeout

### ISSUE THREAD

**Issue by AnkurTank** [tox-dev/filelock#49]
py-filelock documentation has following information.
`timeout (float) – The maximum time waited for the file lock. If timeout <= 0, there is no timeout and this method will block until the lock could be acquired. If timeout is None, the default timeout is used.`

However in actual code when `timeout = 0`  filelock doesn't wait and raises Timeout exception if lock is acquired by someone else, which seems right but doesn't match with documentation.

So documentation should say following.
`timeout (float) – The maximum time waited for the file lock. If timeout < 0, there is no timeout and this method will block until the lock could be acquired. If timeout is None, the default timeout is used.`

**Comment by AdorablePotato** [comment]
Thank you, will be fixed in the next version.
