### ISSUE TITLE
[Request] Add option to disable logger

### ISSUE THREAD

**Issue by Winning117** [tox-dev/filelock#59]
By default this package will always print to a logger, but for my use case it only ends up cluttering the logs with "released, acquired, released, acquired, etc". I'd appreciate it if you could add the option to disable the logger :)

**Comment by liiight** [comment]
You can probably do it yourself via the logging module:
```python

import logging

logging.getLogger('py-filelock.filelock').setLevel(logging.ERROR) # not sure about the logger name but you get the point
```

**Comment by pquentin** [comment]
`logging.getLogger("filelock").setLevel(logging.ERROR)` works

**Comment by gaborbernat** [comment]
We probably should add a section on this into the readme, if you make a PR for this we would be happy to review it, thanks!

**Comment by hkennyv** [comment]
@gaborbernat I believe that now, as of 3.2.0, it should now be:

```python
logging.getLogger("filelock._api").setLevel(logging.DEBUG)
```

I think it makes more sense to keep the logger the same name as the package, which would require changing:

https://github.com/tox-dev/py-filelock/blob/c9b6d90b8d0d6f3971b97ce7bfd1b3402d58220e/src/filelock/_api.py#L7

to:

```python
_LOGGER = logging.getLogger("filelock")
```

How does that sound?

**Comment by gaborbernat** [comment]
Oh you're right 🙂

**Comment by gaborbernat** [comment]
Please put in a PR we'll accept it :blush: (add a test).
