### ISSUE TITLE
platform dependence

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [tox-dev/filelock#71]
I’m not clear about the following:

"The FileLock is platform dependent while the SoftFileLock is not. Use the FileLock if all instances of your application are running on the same host and a SoftFileLock otherwise."

Platform dependence usually means that the code is dependent on a particular OS.  This is not consistent with the second sentence.

**Comment by Jingnan-Jia** [comment]
I guess this is a typo.  Because in the [document](https://filelock.readthedocs.io/en/latest/) the first sentense is: A platform **independent** file lock that supports the with-statement.

**Comment by gaborbernat** [comment]
Hello, if you make a PR for this (with tests) we would be happy to review it, thanks!
