### ISSUE TITLE
filelock should provide universal wheels

### ISSUE THREAD

**Issue by AndrewHoos** [tox-dev/filelock#72]
The `filelock` wheels on pypi.org are not universal:
https://pypi.org/simple/filelock/

e.g. `filelock-3.0.12-py3-none-any.whl`

It would be nice to have universal wheels. They can be built with

    python3 setup.py bdist_wheel --universal

This will produce wheels named:
`filelock-3.0.12-py2.py3-none-any.whl`

Instead of the current name:
`filelock-3.0.12-py3-none-any.whl`

**Comment by graingert** [comment]
@AndrewHoos @benediktschmitt  see #75

**Comment by gaborbernat** [comment]
Done in #87
