### ISSUE TITLE
Reliable over NFS?

### ISSUE THREAD

**Issue by moi90** [tox-dev/filelock#73]
Is SoftFileLock reliable over NFS? What NFS settings are required for SoftFileLock to work properly?

**Comment by moi90** [comment]
SoftFileLock uses `O_WRONLY | O_CREAT | O_EXCL | O_TRUNC`.

According to [man open](https://man7.org/linux/man-pages/man2/open.2.html):

> O_CREAT: If pathname does not exist, create it as a regular file.
> O_EXCL: Ensure that this call creates the file: if this flag is specified in conjunction with O_CREAT, and pathname already exists, then open() fails with the error EEXIST.
> On NFS, O_EXCL is supported only when using NFSv3 or later on kernel 2.6 or later.

This is in compliance with the [NFS FAQ D10](http://nfs.sourceforge.net/#faq_d10):
>  It's worth noting that until early 2.6 kernels, O_EXCL creates were not atomic on Linux NFS clients. Don't use O_EXCL creates and expect atomic behavior among multiple NFS client unless you are running a kernel newer than 2.6.5.

So the answer should be: Yes, on modern systems.

What is the reason for O_TRUNC? It seems to be superfluous, because O_CREAT | O_EXCL prevent the file from being opened if it exists.
> O_TRUNC: If the file already exists and is a regular file and the access mode allows writing (i.e., is O_RDWR or O_WRONLY) it will be truncated to length 0.

**Comment by andyneff** [comment]
I tested this on lusterfs and nfs both the `lock` mount flag enabled and disabled, and "unit tests passed". I do not know enough if this answers any of the reliability questions, but if the tests are good enough, this might be enough to verify it works on "RHEL 7" modern.

**Comment by moi90** [comment]
Great! Then I think this can be closed.
