### ISSUE TITLE
Locking is not exclusive when two threads request for a lock at a very close interval

### ISSUE THREAD

**Issue by fhcat** [tox-dev/filelock#81]
We are using py-filelock 3.0.12 and have experienced a problem when multiple threads are trying to acquire the lock on the same file at almost the same time. This happens quite often in our AWS EC2 instance and causes data corruption. We are just following the examples in the documentation to use the module. Is there any way to avoid this?

**Comment by stephane-archer** [comment]
Do you have the same problem with a local computer or did you observe that only in EC2?

**Comment by fhcat** [comment]
I tried it locally and it seems to work, although my setup on EC2 is hard to simulate. I wrote a multi-threading program to test it and it works on Windows 10.

**Comment by stephane-archer** [comment]
Your EC2 is Linux or windows based? Because it's not the same api between
POSIX and Windows.

**Comment by gaborbernat** [comment]
Hello, if you make a PR for this (with tests) we would be happy to review it, thanks!

**Comment by gaborbernat** [comment]
I'm closing this for lack of feedback, however, if you can provide more information we can reopen it.
