### ISSUE TITLE
locking seems to erase the file!

### ISSUE THREAD

**Issue by Mabooka** [tox-dev/filelock#9]
Hi,
if I do
   with lock.acquire(timeout = 5):
        fp = open(flnm, "a")
        print >> fp, "some text"
        fp.close()
and then look at the file, I only see one line of text in it (no matter what was in it before).
What am I doing wrong?

I am attaching my code that demonstrates the issue.
please run:
1) python issue_filelock.py 1 
   several times, and then 
2) python issue_filelock.py 2

you will see that the file gets truncated. 
And the only difference is one line: 
with lock.acquire(timeout = 5):

[issue_filelock.py.zip](https://github.com/benediktschmitt/py-filelock/files/129459/issue_filelock.py.zip)

**Comment by johaven** [comment]
+1

**Comment by AdorablePotato** [comment]
Hi,

the use case for this library is signalizing different instances of an application, that shared resources are
currently accessed. For example: Some synchronization programs create a lock file during synchronization in the root folder to prevent other instances from doing it to the same time. As soon as the lock file has been removed, the other instance starts the synchronization progress.

If you want to avoid race conditions, you can use either this library like this:

``` python
lock = FileLock(flnm + ".lock")
with lock.acquire(timeout=5):
   with open(flnm, "a") as file:
     file.write("some text")
```

or you take a look at the underlying os functions: https://www.safaribooksonline.com/library/view/python-cookbook/0596001673/ch04s25.html

EDIT: Removing the file is done intentionally as part of the clean up.
